### ISSUE TITLE
bug: 私聊发送语音卡住

### ISSUE THREAD

**Issue by ikechan8370** [whitechi73/OpenShamrock#11]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

私聊发送语音（record）会卡住没有响应，群聊正常。

### 复现 Bug

当发送record类型消息时，使用send_private_msg接口向好友发送消息时会无限卡住没有响应，开启debug后日志正常会打印silk编码的日志。
![image](https://github.com/whitechi73/OpenShamrock/assets/21212372/ce1d41f6-ace9-4967-8a69-1df988fbe0b7)
当使用send_group_msg接口向群聊发送时，一切正常。
此外，send_group_msg接口如果group_id填写为本身不在的群组，会导致shamrock崩溃重启。

## 系统信息

- Shamrock 版本: Shamrock-v1.0.5-dev.41675ed-all
- Android 版本: 12
- 设备的制造商和型号: Realme
- 设备的 CPU 架构:  arm64

**Comment by ikechan8370** [comment]
此外在android x86上发送语音会出现以下报错无法发送语音：
```
[23:49:28] INFO LoadExternalLibrary(name = ffmpegkit_abidetect)
[23:49:28] INFO LoadExternalLibrary(name = avutil)
[23:49:28] INFO LoadExternalLibrary(name = swscale)
[23:49:28] INFO LoadExternalLibrary(name = swresample)
[23:49:28] INFO LoadExternalLibrary(name = avcodec)
[23:49:28] INFO LoadExternalLibrary(name = avformat)
[23:49:28] INFO LoadExternalLibrary(name = avfilter)
[23:49:28] INFO LoadExternalLibrary(name = avdevice)
[23:49:28] INFO LoadExternalLibrary(name = ffmpegkit)
[23:49:28] INFO LoadExternalLibrary(name = ffmpegkit_abidetect)
[23:49:28] ERROR java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.arthenica.ffmpegkit.AbiDetect.getNativeAbi() (tried Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi and Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi__)
	at com.arthenica.ffmpegkit.AbiDetect.getNativeAbi(Native Method)
	at com.arthenica.ffmpegkit.NativeLoader.loadNativeAbi(NativeLoader.java:65)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKit(NativeLoader.java:173)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.<clinit>(FFmpegKitConfig.java:145)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.parseArguments(FFmpegKitConfig.java:1318)
	at com.arthenica.ffmpegkit.FFmpegKit.execute(FFmpegKit.java:167)
	at moe.fuqiuluo.shamrock.utils.AudioUtils.audioToPcm(AudioUtils.kt:140)
	at moe.fuqiuluo.shamrock.utils.AudioUtils.audioToSilk$xposed_release(AudioUtils.kt:77)
	at moe.fuqiuluo.qqinterface.servlet.msg.MessageMaker.createRecordElem-yxL6bBk(MessageMaker.kt:569)
	at moe.fuqiuluo.qqinterface.servlet.msg.MessageMaker.access$createRecordElem-yxL6bBk(MessageMaker.kt:76)
	at moe.fuqiuluo.qqinterface.servlet.msg.MessageMaker$createRecordElem$1.invokeSuspend(Unknown Source:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

[23:49:28] ERROR java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.arthenica.ffmpegkit.AbiDetect.getNativeAbi() (tried Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi and Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi__)
	at com.arthenica.ffmpegkit.AbiDetect.getNativeAbi(Native Method)
	at com.arthenica.ffmpegkit.NativeLoader.loadNativeAbi(NativeLoader.java:65)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKit(NativeLoader.java:173)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.<clinit>(FFmpegKitConfig.java:145)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.parseArguments(FFmpegKitConfig.java:1318)
	at com.arthenica.ffmpegkit.FFmpegKit.execute(FFmpegKit.java:167)
	at moe.fuqiuluo.shamrock.utils.AudioUtils.audioToPcm(AudioUtils.kt:140)
	at moe.fuqiuluo.shamrock.utils.AudioUtils.audioToSilk$xposed_release(AudioUtils.kt:77)
	at moe.fuqiuluo.qqinterface.servlet.msg.MessageMaker.createRecordElem-yxL6bBk(MessageMaker.kt:569)
	at moe.fuqiuluo.qqinterface.servlet.msg.MessageMaker.access$createRecordElem-yxL6bBk(MessageMaker.kt:76)
	at moe.fuqiuluo.qqinterface.servlet.msg.MessageMaker$createRecordElem$1.invokeSuspend(Unknown Source:19)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

```
 然后收到的消息就变成`该消息只支持手机端查看`

**Comment by whitechi73** [comment]
SILK编码的文件正常存在吗？

**Comment by ikechan8370** [comment]
> SILK编码的文件正常存在吗？

文件在的

**Comment by whitechi73** [comment]
> > SILK编码的文件正常存在吗？
> 
> 文件在的

文件大小正常吗？

**Comment by whitechi73** [comment]
- 下载 **AudioLibrary** 语音支持库，请下载对应架构的文件，否则可能无法运行。
- 将全部文件解压到 `Shamrock 主目录` 下的 `lib` 文件夹中

> [AudioLibrary-Arm64](https://github.com/whitechi73/OpenShamrock/blob/master/AudioLibrary-arm64.zip)
> [AudioLibrary-X64](https://github.com/whitechi73/OpenShamrock/blob/master/AudioLibrary-x64.zip)

**Comment by ikechan8370** [comment]
> > > SILK编码的文件正常存在吗？
> > 
> > 
> > 文件在的
> 
> 文件大小正常吗？
正常。根据debug日志的路径找过去的tmpfiles下的文件，mt管理器里可以打开播放。

**Comment by ikechan8370** [comment]
> * 下载 **AudioLibrary** 语音支持库，请下载对应架构的文件，否则可能无法运行。
> * 将全部文件解压到 `Shamrock 主目录` 下的 `lib` 文件夹中
> 
> > [AudioLibrary-Arm64](https://github.com/whitechi73/OpenShamrock/blob/master/AudioLibrary-arm64.zip)
> > [AudioLibrary-X64](https://github.com/whitechi73/OpenShamrock/blob/master/AudioLibrary-x64.zip)

明白了。是我下错架构了。

**Comment by ikechan8370** [comment]
> 是转换出来的SILK文件，正常吗(QQ语音格式是SILK)

才发现原来tmpfiles下面是原始文件。
然后根据代码去找到了amr文件，发现发送群聊和发送私聊时生成的amr文件完全相同，我是这么看的：
1. 发送wav语音到群聊，ptt目录下出现amr文件，正常发送
2. 删除刚才的amr
3. 发送同一语音文件到私聊，ptt目录下出现amr文件，经对比文件名和哈希都和之前的一样。但是请求会卡住，只能手动取消http请求。

**Comment by fuqiuluo** [comment]
> 
> 
> 
> > 是转换出来的SILK文件，正常吗(QQ语音格式是SILK)
> 
> 才发现原来tmpfiles下面是原始文件。
> 然后根据代码去找到了amr文件，发现发送群聊和发送私聊时生成的amr文件完全相同，我是这么看的：
> 1. 发送wav语音到群聊，ptt目录下出现amr文件，正常发送
> 2. 删除刚才的amr
> 3. 发送同一语音文件到私聊，ptt目录下出现amr文件，经对比文件名和哈希都和之前的一样。但是请求会卡住，只能手动取消http请求。
> 
> 
> 

可以把测试音频和这个问题提交到论坛吗？

**Comment by ikechan8370** [comment]
> > > 是转换出来的SILK文件，正常吗(QQ语音格式是SILK)
> > 
> > 
> > 才发现原来tmpfiles下面是原始文件。
> > 然后根据代码去找到了amr文件，发现发送群聊和发送私聊时生成的amr文件完全相同，我是这么看的：
> > 
> > 1. 发送wav语音到群聊，ptt目录下出现amr文件，正常发送
> > 2. 删除刚才的amr
> > 3. 发送同一语音文件到私聊，ptt目录下出现amr文件，经对比文件名和哈希都和之前的一样。但是请求会卡住，只能手动取消http请求。
> 
> 可以把测试音频和这个问题提交到论坛吗？

好哦 我整理以下 咱也是洛守护
