### ISSUE TITLE
bug: v1.0.6.dev运行一段时间后消息无法发出？

### ISSUE THREAD

**Issue by JUST-HK416D** [whitechi73/OpenShamrock#113]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

使用了actions中最新构建的apk和releases中的apk均出现启动后约半小时或一小时后就会无法发送消息，消息一直转圈无法发出，OpenShamrock日志上显示发送消息，暂时还未打开debug模式记录更多日志，晚些时候补充
![M Q)VYK20`CFK7 J(VUKE71](https://github.com/whitechi73/OpenShamrock/assets/90328461/24dd7624-17e9-4c10-b13d-078c24d966b7)
![%(TB~@P)CTUF$I_K6ZT1J 9](https://github.com/whitechi73/OpenShamrock/assets/90328461/d2d25eb1-1f3a-4a5e-941e-1fff000550bb)

### 复现 Bug

使用LSPatch进行嵌入，启动OpenShamrock后在启动QQ，此时可以发送消息，一段时间后就无法发送任何消息

## 系统信息

- Shamrock 版本: v1.0.6.dev
- QQ 版本：8.9.80.12440
- Android 版本: 10.0
- LSPosed 框架版本: LSPatch[0.5.1]
- 设备的制造商和型号: 移动云手机
- 设备的 CPU 架构: 移动云手机

**Comment by JUST-HK416D** [comment]
另外还发现一个问题，当LSPatch嵌入后的QQ安装后，如果OpenShamrock已填写服务端相关配置并开启后，还未登录QQ号时打开QQ会闪退，关闭后登录QQ号后再开启就不会闪退了，不知道是原本设定如此还是Bug

**Comment by JUST-HK416D** [comment]
**发送时日志**
`[17:20:05] DEBUG ReceivePacket(cmd = trpc.msg.olpush.OlPushService.MsgPush)[17:20:05] INFO 群消息(group = Automat Nikonova 94、普通(737059800), uin = 1790376528, id = 1621651354|2469, msg = *ping)[17:20:05] INFO 发送消息(1572489696 | 2469 | 7307553586702914050): [CQ:reply,id=1621651354]PONG！[17:20:07] DEBUG ReceivePacket(cmd = trpc.msg.olpush.OlPushService.MsgPush)`

**发送后出现的一个Exception(不知道是不是这个问题的异常？)**
`[17:20:31] DEBUG ReceivePacket(cmd = trpc.msg.olpush.OlPushService.MsgPush)[17:20:31] WARN java.lang.IllegalStateException: Instance is not ProtoMap for (11)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)`
	
**以及一个不知道是啥东西的提示阻止进入后台模式？**
`[17:22:25] DEBUG ReceivePacket[814306383](cmd = OidbSvc.0x480_9_IMCore, seq = 44834)[17:22:25] DEBUG ReceivePacket[52618969](cmd = SQQzoneSvc.getUndealCount, seq = 44835)[17:22:28] INFO 发送消息(1801243792 | 2470 | 7307554201851418905): 1[17:22:30] DEBUG onDraftUpdate: Contact{chatType=2,peerUid=737059800,guildId=,}|[]|1701422550[17:22:30] DEBUG 阻止进入后台模式！[17:22:30] DEBUG 阻止进入后台模式！`

**同时还发现一个问题，无法通过OpenShamrock发送消息后，也无法从QQ上主动发送消息，同时QQ的消息同步非常慢，我用电脑发送消息到群内，机器人端QQ收不到，大部分群聊的信息也是，仿佛断网一般，重启QQ后解决(有时候得2个都重启)**

机器人端最后接收消息时间
![B_N8Y6SW_VAKA3RFTER1L~5](https://github.com/whitechi73/OpenShamrock/assets/90328461/96e6f3a5-2b4d-45a1-9909-7bf7117aaa90)
电脑端发送的消息时间
![94K}H1TX5HJ)Q9VDN6) KP0](https://github.com/whitechi73/OpenShamrock/assets/90328461/8092d650-d6a9-4436-9467-beb29b583f4b)
以及QQ无法手动发出消息
![W50U7@TKZ}5P@R7})X8GCIB](https://github.com/whitechi73/OpenShamrock/assets/90328461/af8be5c1-fc47-4732-8c49-415382445e14)

**Comment by Simplxss** [comment]
补充：长时间不发送消息（？）似乎还会接收不到消息 基本上每次早上都会出现这种情况 调用发送消息接口后恢复 且会一次性接收到期间所有消息

**Comment by JUST-HK416D** [comment]
> 建议给出全面日志，脱敏后发出

神奇的是，我临时从移动云手机切换到川川云手机后又不会出现这种情况了。。云手机设备或配置问题？但是之前我还有三四个号目前也是在移动云手机上挂着没问题，有点看不太懂，中午我换个QQ号试一下，我在TG群内好像没看到您或者不清楚群内ID，请问有可用TG联系方式吗？可以提供云机查看排查问题。
