### ISSUE TITLE
bug: 不能正常激活，LSPosed中可看到报错

### ISSUE THREAD

**Issue by Asgore-Dreemur** [whitechi73/OpenShamrock#120]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

我在shamrock在后台运行的情况下打开qq，并未弹出模块已激活的toast
打开shamrock主程序也是未激活
LSPosed日志:
```
[ 2023-12-02T22:51:13.285     1000:  1954:  2001 I/LSPosed-Bridge  ] [ INFO] 12-02 22:51:13 (ZygoteArgsHook) @startViaZygote force mount data: 1010539 com.tencent.mobileqq
[ 2023-12-02T22:51:13.842  1010539: 22744: 22744 I/LSPosed-Bridge  ] Loading legacy module moe.fuqiuluo.shamrock from /data/app/~~N4Bo3ld3SLnK5LclpGYddA==/moe.fuqiuluo.shamrock-e8LOLFAwkn2LeWBCmG6qHA==/base.apk
[ 2023-12-02T22:51:14.715  1010539: 22744: 22744 I/LSPosed-Bridge  ]   Loading class moe.fuqiuluo.shamrock.xposed.XposedEntry
[ 2023-12-02T22:51:14.926  1010539: 22744: 22744 I/LSPosed-Bridge  ] Try load fetchEntry's injector.
[ 2023-12-02T22:51:15.267  1010539: 22744: 22885 I/LSPosed-Bridge  ] Classloader inject successfully.
[ 2023-12-02T22:51:15.268  1010539: 22744: 22885 I/LSPosed-Bridge  ] Process Name = com.tencent.mobileqq:MSF
[ 2023-12-02T22:51:16.312  1010539: 22744: 22885 E/LSPosed-Bridge  ] android.content.pm.PackageManager$NameNotFoundException: moe.fuqiuluo.shamrock
	at android.app.ApplicationPackageManager.getApplicationInfoAsUser(ApplicationPackageManager.java:517)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:500)
	at android.app.ApplicationPackageManager.getApplicationInfo(ApplicationPackageManager.java:494)
	at moe.fuqiuluo.shamrock.xposed.actions.AntiDetection.antiFindPackage(AntiDetection.kt:70)
	at moe.fuqiuluo.shamrock.xposed.actions.AntiDetection.invoke(AntiDetection.kt:26)
	at moe.fuqiuluo.shamrock.xposed.loader.ActionLoader.runFirst(ActionLoader.kt:33)
	at moe.fuqiuluo.shamrock.xposed.XposedEntry.execStartupInit(XposedEntry.kt:137)
	at moe.fuqiuluo.shamrock.xposed.XposedEntry.access$execStartupInit(XposedEntry.kt:25)
	at moe.fuqiuluo.shamrock.xposed.XposedEntry$entryMQQ$startup$1.invoke(XposedEntry.kt:63)
	at moe.fuqiuluo.shamrock.xposed.XposedEntry$entryMQQ$startup$1.invoke(XposedEntry.kt:52)
	at moe.fuqiuluo.shamrock.tools.XposedKt$afterHook$1.afterHookedMethod(Xposed.kt:55)
	at ZJPpru.gBhR.Ho.FCxSSEw.XposedBridge$LegacyApiSupport.handleAfter(Unknown Source:33)
	at J.callback(Unknown Source:292)
	at LSPHooker_.run(Unknown Source:11)
	at com.tencent.qqnt.startup.NtStartupDispatcher.c(P:6)
	at com.tencent.qqnt.startup.NtStartupDispatcher.a(P:1)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:2)
	at com.tencent.qqnt.startup.NtStartupDispatcher$dispatcher$2.invoke(P:1)
	at com.tencent.qqnt.startup.c.d(P:1)
	at com.tencent.qqnt.startup.c.f(Unknown Source:0)
	at com.tencent.qqnt.startup.b.run(Unknown Source:2)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
	at java.lang.Thread.run(Thread.java:1012)
```

我在分身和主用户中都进行了尝试，看起来包名没问题，是否是因为一些前面或后面的空格?

### 复现 Bug

激活shamrock，打开qq

## 系统信息

- Shamrock 版本: 1.0.7-dev
- Android 版本: 13
- LSPosed 框架版本: 1.9.2 7034
- 设备的制造商和型号: xiaomi Redmi 5 plus
- 设备的 CPU 架构: arm64-v8a

**Comment by Asgore-Dreemur** [comment]
shamrock本体并没有任何日志

**Comment by Asgore-Dreemur** [comment]
看了下，我装了隐藏应用列表，对qq隐藏了shamrock，所以报错

**Comment by HDTianRu** [comment]
我记得原来的版本隐藏shamrock了也能激活，现在不行了吗
