### ISSUE TITLE
bug: 请求发送一条消息后马上断开WS连接导致QQ进程退出

### ISSUE THREAD

**Issue by Miuzarte** [whitechi73/OpenShamrock#137]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

应该能实锤是post之后马上断开ws连接就会触发，不过完全没有日志，异常跟踪捕获不到
猜测是QQ想返回响应结果但是ws没了

![image](https://github.com/whitechi73/OpenShamrock/assets/66856838/af8702af-2efd-43f1-8878-780594aac128)
手机时间比PC快了两秒钟，时间是对得上的
```log
[15:17:35] WARN onMsgPush(msgType: 528): java.lang.IllegalStateException: Tag 13 not found
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

[15:17:40] INFO 预发送消息(825428636 | 6410 | 7309377465918605569)
[15:17:40] WARN WSServer断开(192.168.1.100:2320/): 1006,,true
[15:17:40] INFO Update message info from 6410 to 6411
[15:17:40] INFO 消息发送: user_id, code: 0 

没了
```

### 复现 Bug

请求发送一条消息，在发送成功返回响应前断开WS连接

## 系统信息

- Shamrock 版本: [Shamrock-v1.0.7-dev.ab6e431](https://github.com/whitechi73/OpenShamrock/actions/runs/7109046062)
- Android 版本: 14
- LSPosed 框架版本: 1.9.2(7024)
- 设备的制造商和型号: Xiaomi Redmi K20 Pro
- 设备的 CPU 架构: Arm64

**Comment by whitechi73** [comment]
> <img alt="Snipaste_2023-12-08_17-26-28" width="752" src="https://private-user-images.githubusercontent.com/20863202/289025364-e199fa6d-d097-49d1-8aea-238e61e09ff9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIxMTAxMzksIm5iZiI6MTcwMjEwOTgzOSwicGF0aCI6Ii8yMDg2MzIwMi8yODkwMjUzNjQtZTE5OWZhNmQtZDA5Ny00OWQxLThhZWEtMjM4ZTYxZTA5ZmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjA5VDA4MTcxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTc5ZjdhYTc0ZDA1NTc2NTI4MzhlODJhY2NiZDVjYzk2MDU1ZDY4OGE4YzU1ZDAzOWEyYjQ3YWI5MDk5NGZlNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.iC2M3IWjMcmCLhPJchme1ArzowNsO7glpsFB1oDNLS4">
> 我的则是这样的情况

这个是服务端拒绝连接，一般是token不对导致的。
