### ISSUE TITLE
feat: 是否有可能在QQ无法发送消息的时候进行Socket或者Http回调通知？

### ISSUE THREAD

**Issue by JUST-HK416D** [whitechi73/OpenShamrock#141]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭

- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的功能请求尚未在 Issues 列表中提出.
- 确保您的功能请求是与 Shamrock 相关的，且可以实现.

### 描述功能

比如被TX小控要求操作图形验证码的时候，无法发出消息，这个破号经常每日一次，也不知道啥时候会，只能手动ping或者发指令的时候没反应上去看
![T JJ}XM%6G3MV8%453X7_WI](https://github.com/whitechi73/OpenShamrock/assets/90328461/97b85fd5-b6db-420c-9a46-0297abd6d75d)

**Comment by JUST-HK416D** [comment]
> 可以看看日志吗？

我先解了这次的验证码，明天应该还会出现，我到时候抓取一下

**Comment by JUST-HK416D** [comment]
> 可以看看日志吗？
云手机不太好复制，临时抓取的日志，会是code46返回码？
```LOG
[23:47:57] INFO 消息发送: 592412193, code: 46
[23:47:58] INFO 预发送消息(1271443989 | 539237 | 7310251140891728898)
[23:47:58] DEBUG ReceivePacket(cmd = trpc.msg.olpush.OlPushService.MsgPush)
[23:47:58] WARN onMsgPush(msgType: 732): java.lang.IllegalStateException: Tag 2 not found
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.ru
```

**Comment by JUST-HK416D** [comment]
嗯，我还是先这样抽空测试然后解验证吧，目前是五六个号里面出的一个这个，确实也蛮怪

**Comment by Simplxss** [comment]
给你个曲线救国的方法, 可以打开上报自身消息, 然后就知道发送成功了没有.

**Comment by Zyy955** [comment]
46就是被封禁了群聊，手动上号解除就能用了，跟shamrock没啥关系，icqq跟gocq都是如此
