### ISSUE TITLE
bug: 群成员邀请成员入群的请求事件没有正确上报

### ISSUE THREAD

**Issue by MejiroRina** [whitechi73/OpenShamrock#156]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

当群成员邀请好友入群时，出现在群通知里的邀请入群申请没有上报，或是偶发如下log的错误
>[02:12:22] DEBUG registerHandler[1072815094](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = 86722)
[02:12:22] DEBUG registerHandler[1072815095](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = 86723)
[02:12:22] DEBUG registerHandler[1072815096](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = 86724)
[02:12:22] DEBUG registerHandler[1072815097](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = 86725)
[02:12:22] DEBUG registerHandler[1072815098](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = 86726)
[02:12:22] DEBUG registerHandler[1072815099](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = 86727)
[02:12:22] DEBUG registerHandler[1072815100](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = 86728)
[02:12:22] DEBUG registerHandler[1072815101](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = 86729)
[02:12:22] WARN java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:32)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:102)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)`

### 复现 Bug

手动处理邀请入群申请时还会出现上报以下event的情况:
>{
   "time":1702750036,
   "self_id": 166766,
   "post_type":"request",
   "request_type":"group",
   "flag":"************",
   "sub_type":"add",
   "user_id":166766,
   "group_id": 88887621
}

该user_id为bot的qq号，而非被邀请进群的人的QQ号

## 系统信息

- Shamrock 版本: 4ef014a
- Android 版本: 12
- LSPosed 框架版本: LSPatch v0.6.0
- 设备的制造商和型号: MuMu12
- 设备的 CPU 架构: x86_64

**Comment by MejiroRina** [comment]
啊，可能表述还是有点含糊，是这种情况没有正确上报
刚刚测了下 6107ec6 也是没正确处理的
![IMG_0158](https://github.com/whitechi73/OpenShamrock/assets/70424266/2bb3d1e8-bdc8-4b8d-b1a5-6ffba0cec6b0)
DEBUG里可以看见

> DEBUG registerHandler[num](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = num)

这样的信息，但是没有推送入群申请

**Comment by ikechan8370** [comment]
> 啊，可能表述还是有点含糊，是这种情况没有正确上报 刚刚测了下 [6107ec6](https://github.com/whitechi73/OpenShamrock/commit/6107ec6ffbf7fa02186f706c2514ba376530763b) 也是没正确处理的 ![IMG_0158](https://private-user-images.githubusercontent.com/70424266/291027240-2bb3d1e8-bdc8-4b8d-b1a5-6ffba0cec6b0.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDI3OTE0ODAsIm5iZiI6MTcwMjc5MTE4MCwicGF0aCI6Ii83MDQyNDI2Ni8yOTEwMjcyNDAtMmJiM2QxZTgtYmRjOC00YjhkLWIxYTUtNmZmYmEwY2VjNmIwLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxN1QwNTMzMDBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03MzY3NDBjMDZhMzBiZDM3MWZmZTQwYzQ2MWI5OTJiM2M3MWQ5NWUwZDM1MmM2MDUzMzcxZjkzMGNkYmU0NTVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hsgS6tY44OUOmw6nadYxKBp5CyuQoULjBrweVGylGdU) DEBUG里可以看见
> 
> > DEBUG registerHandler[num](cmd = ProfileService.Pb.ReqSystemMsgNew.Group, seq = num)
> 
> 这样的信息，但是没有推送入群申请

有日志吗？那个debug就是shamrock在主动查询请求的信息

**Comment by MejiroRina** [comment]
除此之外没有更多的日志了，也没有看见报错信息

**Comment by ikechan8370** [comment]
> 除此之外没有更多的日志了，也没有看见报错信息 而且一般入群通知是可以正常收到的，就这类不行

这类指的是邀请进群吗？shamrock日志有对应的信息吗？info的。

**Comment by MejiroRina** [comment]
对的
Shamrock里面出现了debug信息之后没有出现INFO 入群申请
正常流程入群是有INFO 入群申请的

**Comment by MejiroRina** [comment]
目前测试了QQ8.9.85和8.9.93都没有推送这种请求，Shamrock上没有对应的INFO，websocket里也没有产生对应的event（一般情况入群是有对应group_add event的）

**Comment by Mythologyli** [comment]
这个 issue 感觉需要重新打开，因为并没有解决

问题的根源在于邀请入群的时候并不会有 `trpc.msg.olpush.OlPushService.MsgPush`，而在手动通过/拒绝后则会产生 `trpc.msg.olpush.OlPushService.MsgPush` 并触发 `onGroupApply`，产生错误的事件

复现方法：将群组设置为邀请加群需要验证，然后非管理用户邀请另一个用户加群。邀请加群时的相关日志如下（23:11:54）：

![9d0d958739778a0440e64058ebe3a685](https://github.com/whitechi73/OpenShamrock/assets/15955880/df1ce5e2-6baf-4110-9ff1-764bec09d6c6)

**Comment by MejiroRina** [comment]
对的，手动拒绝/同意之后会产生一个奇怪的group_add事件，不过这个情况下group_increase是可以正确推送的
而且这类“由一个群员邀请另一个好友进入群聊的申请”由于shamrock没法处理，我已经对特定群聊使用特定框架来处理这个事件
