### ISSUE TITLE
bug: 消息重复发送

### ISSUE THREAD

**Issue by Miuzarte** [whitechi73/OpenShamrock#187]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

只POST了一次发送请求，在手Q客户端显示为发了四条，第三视角看收到了三条

似乎只有发送`文+在线图片`一起的消息才会发生这种情况

QQ `8.9.88` 和 `9.0.0.14110` 都多次复现过

[13:39:19]POST: 
```
{"action":"send_group_msg","echo":"send_group_msg_1704346759384347036","params":{"group_id":group_id,"message":"anything\n[CQ:image,file=...]"}}
```

[13:39:43]RECV:
```
{"status":"ok","retcode":0,"data":{"message_id":1638873553,"time":1704346779},"echo":"send_group_msg_1704346759384347036"}
```

LOG:
```
[13:39:14] WARN onMsgPush(msgType: 528, subType: 35): java.lang.IllegalStateException: Tag 1 not found
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

[13:39:20] INFO 预发送消息(968529291 | 1463575 | 7320113596744821762)
[13:39:25] WARN onMsgPush(msgType: 732, subType: 16): java.lang.IllegalStateException: Tag 5 not found
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

[13:39:26] INFO 预发送消息(160088463 | 1463575 | 7320113621113468674)
[13:39:33] INFO 预发送消息(219154274 | 1463575 | 7320113652796070402)
[13:39:39] INFO 预发送消息(1638873553 | 1463575 | 7320113678367147266)
[13:39:41] INFO 消息发送: 660996459, code: -1 rich media transfer failed
[13:39:42] INFO Update message info from 1463575 to 1463576
[13:39:42] INFO 消息发送: 660996459, code: 0 
[13:39:42] INFO 消息发送: 660996459, code: 0 
[13:39:42] INFO Update message info from 1463575 to 1463577
[13:39:43] INFO Update message info from 1463575 to 1463578
[13:39:43] INFO 消息发送: 660996459, code: 0 
[13:39:46]...（另一个群收到了消息）
```
### 复现 Bug

发送`文+在线图片`的群聊消息

## 系统信息

- Shamrock 版本: [[fix] #186 2c1bd9e](https://github.com/whitechi73/OpenShamrock/commit/2c1bd9e726c99e679c9f9c8b84b6b8b4403cbef3)
- Android 版本: 14
- LSPosed 框架版本: 1.9.2 7042
- 设备的制造商和型号: Redmi K20 Pro
- 设备的 CPU 架构: Arm64
- QQ 版本: 9.0.0.14110

**Comment by MinkGu** [comment]
+1，同样遇到了此类问题

**Comment by okashi-ya** [comment]
消息重复发送的问题本人也出现过
根据一周多以来的跟踪，当电脑性能不太好的时候感觉触发概率很高。
一个复现概率较大的场景：当硬盘IO100%（例如视频转换期间），此时发送消息有很大概率会重复发多次。

而且此时bot侧会收到ActionFailed超时的报错，但是复现不稳定，并不是必现，最好让系统硬盘满载时再尝试

**Comment by ikechan8370** [comment]
可能是触发了失败/超时的机制，然后shamrock重试了。

**Comment by yixinNB** [comment]
我也遇到过. 我用的是WebSocket. 经过排查,是同时**连接了两个客户端**  
换句话说, shamrock同一个服务器创建了两个obj  
概率还算比较小, **重启**基本都能解决

**Comment by Miuzarte** [comment]
> 我也遇到过. 我用的是WebSocket. 经过排查,是同时**连接了两个客户端** 换句话说, shamrock同一个服务器创建了两个obj 概率还算比较小, **重启**基本都能解决

我更倾向于网络操作超时导致的重发吧，因为我双开的另一个号只连接了一个机器人端也出现了这种情况

**Comment by yixinNB** [comment]
> > 我也遇到过. 我用的是WebSocket. 经过排查,是同时**连接了两个客户端** 换句话说, shamrock同一个服务器创建了两个obj 概率还算比较小, **重启**基本都能解决
> 
> 我更倾向于网络操作超时导致的重发吧，因为我双开的另一个号只连接了一个机器人端也出现了这种情况

我检查过ws服务器, 确实是有两个client**同时&长时间在线**, 导致shamrock的同一个事件我的ws服务器处理了两次=>执行了两次回复

**Comment by Miuzarte** [comment]
> > > 我也遇到过. 我用的是WebSocket. 经过排查,是同时**连接了两个客户端** 换句话说, shamrock同一个服务器创建了两个obj 概率还算比较小, **重启**基本都能解决
> > 
> > 
> > 我更倾向于网络操作超时导致的重发吧，因为我双开的另一个号只连接了一个机器人端也出现了这种情况
> 
> 我检查过ws服务器, 确实是有两个client**同时&长时间在线**, 导致shamrock的同一个事件我的ws服务器处理了两次=>执行了两次回复

你的情况是两个被动ws？

**Comment by yixinNB** [comment]
> > > > 我也遇到过. 我用的是WebSocket. 经过排查,是同时**连接了两个客户端** 换句话说, shamrock同一个服务器创建了两个obj 概率还算比较小, **重启**基本都能解决
> > > 
> > > 
> > > 我更倾向于网络操作超时导致的重发吧，因为我双开的另一个号只连接了一个机器人端也出现了这种情况
> > 
> > 
> > 我检查过ws服务器, 确实是有两个client**同时&长时间在线**, 导致shamrock的同一个事件我的ws服务器处理了两次=>执行了两次回复
> 
> 你的情况是两个被动ws？

![Screenshot_20240105_211810_moe fuqiuluo shamrock](https://github.com/whitechi73/OpenShamrock/assets/58894205/39d56ae4-a06a-4447-afb9-cba0f26e8845)

**Comment by MoRanYue** [comment]
> 我也遇到过. 我用的是WebSocket. 经过排查,是同时**连接了两个客户端**  
> 换句话说, shamrock同一个服务器创建了两个obj  
> 概率还算比较小, **重启**基本都能解决

这里也是这样的呀。

我想，可能是因为，这里使用了 墓碑模式 Smillet方案，而墓碑模式会在应用空闲，且处于后台时暂时关闭网络连接。
而在之后重新唤醒QQ时，在Bot后端，可以发现，有多次客户端连接。

**Comment by JUST-HK416D** [comment]
同遇到该问题，偶发![image](https://github.com/whitechi73/OpenShamrock/assets/90328461/06417893-6ee2-4d14-93f9-7ae4f211781a)

**Comment by whitechi73** [comment]
如果问题依旧出现，请重新开启issue

**Comment by cpuopt** [comment]
还是有问题，重复的消息2~4条

**Comment by cpuopt** [comment]
用的是[b9cfe73](https://github.com/whitechi73/OpenShamrock/commit/b9cfe73eae2b7fc0e320d2f58eea64a18929d3dc)

DEBUG 日志如下
```
[22:16:23] INFO 群消息(group = ###########(我的群号), uin = 发送人qq, id = 1969268026|224730, msg = /搜图[CQ:image,file=8d736d4c7ca09c24751f98dab99e8fd3,url=http://gchat.qpic.cn/gchatpic_new/0/0-0-8D736D4C7CA09C24751F98DAB99E8FD3/0?term=2])
[22:16:23] INFO 预发送消息(1337775130 | 224730 | 7325070946994283522)
[22:16:23] DEBUG ReceivePacket[266547719](cmd = MessageSvc.PbSendMsg, seq = 80386)
[22:16:23] INFO Update message info from 224730 to 224731
[22:16:24] INFO 消息发送: 我的群号, code: 0 
[22:16:24] DEBUG ReceivePacket(cmd = trpc.msg.olpush.OlPushService.MsgPush)
[22:16:33] DEBUG WebSocketClient心跳: 机器人qq号

==========上面一条消息正常发送，下面是在qq里看重复3次的消息==========

[22:16:38] INFO 预发送消息(1842445369 | 224731 | 7325071011133423874)
[22:16:38] DEBUG ReceivePacket[-388063580](cmd = ImgStore.GroupPicUp, seq = 80387)
[22:16:38] DEBUG ReceivePacket[1281342879](cmd = OnlinePush.ReqPush, seq = -1844873468)
[22:16:39] DEBUG ReceivePacket[-388063578](cmd = ImgStore.GroupPicUp, seq = 80389)
[22:16:42] DEBUG ReceivePacket[-388063555](cmd = ImgStore.GroupPicUp, seq = 80391)
[22:16:42] INFO 预发送消息(890219194 | 224731 | 7325071023776634882)
[22:16:45] INFO 预发送消息(1110027561 | 224731 | 7325071040874601474)
[22:16:45] DEBUG ReceivePacket[-1636157864](cmd = ImgStore.GroupPicUp, seq = 680)
[22:16:48] DEBUG WebSocketClient心跳: 机器人qq号
[22:16:48] INFO 预发送消息(573497676 | 224731 | 7325071054765450754)
[22:16:48] DEBUG ReceivePacket[-388063553](cmd = ImgStore.GroupPicUp, seq = 80393)

[22:16:53] 这个时间，nonebot2那边报了ActionFailed: ActionFailed(status='failed', retcode=35000, data={}, message='发送消息超时', echo='67')

[22:17:00] INFO 消息发送: 我的群号, code: -1 rich media transfer failed
[22:17:00] DEBUG onRichMediaUploadComplete(FileTransNotifyInfo{fileModelId=7325071019502161323,msgElementId=7325071019502161323,msgId=7325071011133423874,fileId=2894252088,fileProgress=0,fileSpeed=0,fileErrCode=1004015,fileErrMsg=,fileDownType=1,thumbSize=0,filePath=/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/chatpic/chatraw/953/Cache_-60d05308ea608953,totalSize=573734,trasferStatus=5,step=5,commonFileInfo=CommonFileInfo{fileModelId=7325071019502161323,msgId=7325071011133423874,elemId=7325071019502161323,uuid=2894252088,subId=,fileName=95C069D36D8D342E7EEBDB5B6F5D8240.jpg,fileSize=573734,msgTime=0,peerUid=我的群号,chatType=2,md5=95c069d36d8d342e7eebdb5b6f5d8240,md510m=,sha=,sha3=,parent=null,favId=null,bizType=0,},fileSrvErrCode=0,clientMsg=,businessId=0,})
[22:17:00] DEBUG ReceivePacket[-388063552](cmd = ImgStore.GroupPicUp, seq = 80394)
[22:17:00] DEBUG onRichMediaUploadComplete(FileTransNotifyInfo{fileModelId=7325071036545805516,msgElementId=7325071036545805516,msgId=7325071023776634882,fileId=2442958244,fileProgress=0,fileSpeed=0,fileErrCode=0,fileErrMsg=,fileDownType=1,thumbSize=0,filePath=/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/chatpic/chatraw/953/Cache_-60d05308ea608953,totalSize=573734,trasferStatus=4,step=0,commonFileInfo=CommonFileInfo{fileModelId=7325071036545805516,msgId=7325071023776634882,elemId=7325071036545805516,uuid=2442958244,subId=,fileName=95C069D36D8D342E7EEBDB5B6F5D8240.jpg,fileSize=573734,msgTime=0,peerUid=我的群号,chatType=2,md5=95c069d36d8d342e7eebdb5b6f5d8240,md510m=,sha=,sha3=,parent=null,favId=null,bizType=0,},fileSrvErrCode=0,clientMsg=,businessId=0,})
[22:17:00] DEBUG ReceivePacket[-388063550](cmd = ImgStore.GroupPicUp, seq = 80396)
[22:17:00] DEBUG onRichMediaUploadComplete(FileTransNotifyInfo{fileModelId=7325071050330412004,msgElementId=7325071050330412004,msgId=7325071040874601474,fileId=3181007478,fileProgress=0,fileSpeed=0,fileErrCode=0,fileErrMsg=,fileDownType=1,thumbSize=0,filePath=/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/chatpic/chatraw/953/Cache_-60d05308ea608953,totalSize=573734,trasferStatus=4,step=0,commonFileInfo=CommonFileInfo{fileModelId=7325071050330412004,msgId=7325071040874601474,elemId=7325071050330412004,uuid=3181007478,subId=,fileName=95C069D36D8D342E7EEBDB5B6F5D8240.jpg,fileSize=573734,msgTime=0,peerUid=我的群号,chatType=2,md5=95c069d36d8d342e7eebdb5b6f5d8240,md510m=,sha=,sha3=,parent=null,favId=null,bizType=0,},fileSrvErrCode=0,clientMsg=,businessId=0,})
[22:17:01] DEBUG ReceivePacket[266547749](cmd = MessageSvc.PbSendMsg, seq = 80395)
[22:17:01] INFO Update message info from 224731 to 224732
[22:17:01] INFO 消息发送: 我的群号, code: 0 
[22:17:01] DEBUG ReceivePacket(cmd = trpc.msg.olpush.OlPushService.MsgPush)
[22:17:01] DEBUG ReceivePacket[-388063548](cmd = ImgStore.GroupPicUp, seq = 80398)
[22:17:01] DEBUG onRichMediaUploadComplete(FileTransNotifyInfo{fileModelId=7325071063047777065,msgElementId=7325071063047777065,msgId=7325071054765450754,fileId=3116430046,fileProgress=0,fileSpeed=0,fileErrCode=0,fileErrMsg=,fileDownType=1,thumbSize=0,filePath=/storage/emulated/0/Android/data/com.tencent.mobileqq/Tencent/MobileQQ/chatpic/chatraw/953/Cache_-60d05308ea608953,totalSize=573734,trasferStatus=4,step=0,commonFileInfo=CommonFileInfo{fileModelId=7325071063047777065,msgId=7325071054765450754,elemId=7325071063047777065,uuid=3116430046,subId=,fileName=95C069D36D8D342E7EEBDB5B6F5D8240.jpg,fileSize=573734,msgTime=0,peerUid=我的群号,chatType=2,md5=95c069d36d8d342e7eebdb5b6f5d8240,md510m=,sha=,sha3=,parent=null,favId=null,bizType=0,},fileSrvErrCode=0,clientMsg=,businessId=0,})
[22:17:01] DEBUG ReceivePacket[266547751](cmd = MessageSvc.PbSendMsg, seq = 80397)
[22:17:01] INFO Update message info from 224731 to 224733
[22:17:01] INFO 消息发送: 我的群号, code: 0 
[22:17:01] DEBUG ReceivePacket(cmd = trpc.msg.olpush.OlPushService.MsgPush)
[22:17:01] DEBUG ReceivePacket[266547753](cmd = MessageSvc.PbSendMsg, seq = 80399)
[22:17:01] INFO Update message info from 224731 to 224734
[22:17:01] INFO 消息发送: 我的群号, code: 0 
[22:17:02] DEBUG ReceivePacket(cmd = trpc.msg.olpush.OlPushService.MsgPush)
[22:17:03] DEBUG WebSocketClient心跳: 机器人qq号
[22:17:18] DEBUG WebSocketClient心跳: 机器人qq号
[22:17:33] DEBUG WebSocketClient心跳: 机器人qq号
[22:17:47] DEBUG ReceivePacket[1969426475](cmd = OnlinePush.ReqPush, seq = -1845185539)
[22:17:48] DEBUG WebSocketClient心跳: 机器人qq号
[22:18:03] DEBUG WebSocketClient心跳: 机器人qq号
```

**Comment by cpuopt** [comment]
据我观察，某些消息（单图片或富文本）从消息预发送至得到rich media transfer failed报错约22秒左右。我怀疑是tx的图片鉴黄系统在起作用。
例如上面我发的日志，消息的超时时间是4秒，预发送4秒后重试，重试3次全部失败。但是3次重试会在首次发送得到报错rich media transfer failed后同时发送成功。
实测把超时时间设置为30秒，在22秒左右收到rich media transfer failed，随后第一次重试直接成功，并且不会返回ActionFailed（可以拿到message_id，这对我很重要）

[超时时间位置](https://github.com/whitechi73/OpenShamrock/blob/master/xposed/src/main/java/moe/fuqiuluo/shamrock/helper/MessageHelper.kt#L81)

然后，这个bug大概是修下面这个bug产生的
[相关的issue #109 ](https://github.com/whitechi73/OpenShamrock/issues/109)

**Comment by ikechan8370** [comment]
意思是说对媒体消息的超时时间估算的太小了，你实测调大了就可以了吗？发自我的 iPhone在 2024年1月20日，22:46，cpufan ***@***.***> 写道：﻿
据我观察，某些消息（单图片或富文本）从消息预发送至得到rich media transfer failed报错约22秒左右。我怀疑是tx的图片鉴黄系统在起作用。
例如上面我发的日志，消息的超时时间是4秒，预发送4秒后重试，重试3次全部失败。但是3次重试会在首次发送得到报错rich media transfer failed后同时发送成功。
实测把超时时间设置为30秒，在22秒左右收到rich media transfer failed，随后第一次重试直接成功，并且不会返回ActionFailed（可以拿到message_id，这对我很重要）
超时时间位置
然后，这个bug大概是修下面这个bug产生的
相关的issue #109

**Comment by cpuopt** [comment]
> 意思是说对媒体消息的超时时间估算的太小了，你实测调大了就可以了吗？发自我的 iPhone在 2024年1月20日，22:46，cpufan ***@***.***> 写道：﻿
> 据我观察，某些消息（单图片或富文本）从消息预发送至得到rich media transfer failed报错约22秒左右。我怀疑是tx的图片鉴黄系统在起作用。
> 例如上面我发的日志，消息的超时时间是4秒，预发送4秒后重试，重试3次全部失败。但是3次重试会在首次发送得到报错rich media transfer failed后同时发送成功。
> 实测把超时时间设置为30秒，在22秒左右收到rich media transfer failed，随后第一次重试直接成功，并且不会返回ActionFailed（可以拿到message_id，这对我很重要）
> 超时时间位置
> 然后，这个bug大概是修下面这个bug产生的
> 相关的issue #109 
> 
> —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you commented.Message ID: ***@***.***>

在这种首次发送22秒必失败的特殊情况，确实估算时间不适用。他这个22秒和数据大小没有关系，感就像是抽查鉴黄一样。而且发过的图，过一会儿再发一次，也不一定能直接成功。

对的，我改到30秒，在22秒就能收到transfer failed，触发重试，重试第一次就直接成功了。
从上面日志也能看出来，重试的三次全是在收到transfer failed后同时成功的。
就是不知道改长超时时间会不会影响其他地方。
