### ISSUE TITLE
bug: Lack of param type

### ISSUE THREAD

**Issue by SilianZ** [whitechi73/OpenShamrock#217]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

```
[23:02:55] ERROR moe.fuqiuluo.shamrock.helper.ParamsException: Lack of param type
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

这是我使用 aiocqhttp 对接 OpenShamrock 时遇到的报错，

与此同时，aiocqhttp 端也出现了如下报错：

```
aiocqhttp.exceptions.NetworkError: WebSocket API call timeout
```

### 复现 Bug

在群内通过 OpenShamrock 往 aiocqhttp 端发送消息时会出现该报错。

通过被动 WebSocket 连接。

OpenShamrock 和 aiocqhttp 端不在同一台设备上，但在同一个局域网内。

## 系统信息

- Shamrock 版本: 1.0.7.r261.c39c2a1
- Android 版本: 12
![image](https://github.com/whitechi73/OpenShamrock/assets/113701655/c8034cdd-b176-4821-896c-47ffda28ea6a)
- 使用 MuMu 模拟器 12

**Comment by whitechi73** [comment]
请问您发送的是什么消息呢？消息内容可否提供？

**Comment by SilianZ** [comment]
[image0.jpeg]

机器人在第一次被输入命令发送第一次消息时，会出现以下报错，但在之后的几次命令调用中，都会正常回复。

在过了很长一段时间后，再次输入命令，会继续出现上述情况。

这似乎是因为机器人在第一次输入命令后，会发出“戳一戳”动作，而 OpenShamrock 不支持该动作造成的。

机器人的主要代码在 https://github.com/Teahouse-Studios/akari-bot。

**Comment by whitechi73** [comment]
原因很简单，shamrock的戳一戳使用的是`touch`作为key，而`poke`是gocq的戳一戳key，传递`poke`消息需要参数type，故出现这个报错。
