### ISSUE TITLE
bug: 合并转发消息发送失败

### ISSUE THREAD

**Issue by XHLiang0** [whitechi73/OpenShamrock#241]
### 描述 Bug

合并转发类信息发送基本上都会出问题，不确定原因，报错信息如下（举例使用xiaoyao-cvs-plugin更新抽卡记录指令，事实上包括扫码登录指令本身也会出现类似问题，情况较多）
[MiaoYz][13:55:58.220][ERRO] 发送消息错误:[{"test":true,"message":[{"type":"node","data":{"id":1379586952}}],"data":{"type":"test","text":"forward","app":"com.tencent.multimsg","meta":{"detail":{"news":[{"text":"1"}]},"resid":"","uniseq":"","summary":""}}}]
[MiaoYz][13:55:58.220][ERRO] TypeError: Cannot read properties of undefined (reading 'msg')
    at Object.array (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/Lain-plugin/lib/common/common.js:142:44)
    at Shamrock.getShamrock (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/Lain-plugin/adapter/shamrock/index.js:1216:19)
    at Shamrock.sendReplyMsg (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/Lain-plugin/adapter/shamrock/index.js:1179:53)
    at ICQQEvent.e.reply [as replyNew] (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/Lain-plugin/adapter/shamrock/index.js:890:48)
    at e.reply (file:///root/TRSS_AllBot/Miao-Yunzai/lib/plugins/loader.js:532:28)
    at e.reply [as _reply] (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/yunzai-c-v-plugin/apps/%E6%B6%88%E6%81%AF%E9%A3%8E%E6%8E%A7%E5%A4%84%E7%90%86.js:31:23)
    at Object.replyMake (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/model/mys/utils.js:81:5)
    at async Module.gclog (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/apps/user.js:179:2)
    at async atlas.dispatch (file:///root/TRSS_AllBot/Miao-Yunzai/plugins/xiaoyao-cvs-plugin/adapter/index.js:47:19)
    at async PluginsLoader.deal (file:///root/TRSS_AllBot/Miao-Yunzai/lib/plugins/loader.js:292:52)
[MiaoYz][13:55:58.222][ERRO] ApiRejection { code: -60, message: 'empty message' }

### 复现 Bug

举例可使用xiaoyao-cvs-plugin调用扫码登录指令、更新抽卡记录指令等均可复现

## 系统信息

- Shamrock 版本: 1.0.8.r320.2c8094c
- 系统版本：Flyme 10.24.1.15 Daily
- Android 版本: 13.0（1682851189）
- LSPosed 框架版本: 1.9.2（7024）
- 设备的制造商和型号: MEIZU 18
- 设备的 CPU 架构: Snapdragon 888 (Lahaina)

**Comment by Zyy955** [comment]
这边于shamrock无关，稍后我来处理
