### ISSUE TITLE
bug: 合并转发图片显示【该消息类型暂不支持查看】

### ISSUE THREAD

**Issue by ycly901** [whitechi73/OpenShamrock#280]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

合并消息转发图片，pc端查看时空白，手机端查看显示【该消息类型暂不支持查看】

### 复现 Bug

发送“#xx过略”（例如：草神攻略）
实际图片已发送给bot自己，在合并转发后，无法正常查看图片
## 系统信息

- Shamrock 版本: 1.0.9.r404.d92d1da
- Android 版本: 12
- LSPosed 框架版本: 1.9.2(使用的LSPatch)
- 设备的制造商和型号: MUMU模拟器
- 设备的 CPU 架构: X86_64

详情日志：
342341236 | 7342708577281620867 | 50306], msg = #草神攻略)[10:59:28] INFO 消息发送: 173927580, code: 0 [10:59:29] INFO 消息发送: 173927580, code: 0 [10:59:30] INFO 消息发送: 173927580, code: 0 [10:59:31] INFO 消息发送: 173927580, code: 0 [10:59:31] INFO 消息发送: 173927580, code: 0 [10:59:32] ERROR java.lang.IllegalStateException: 文件下载失败: https://c2cpicdw.qpic.cn/offpic_new/0/0-0-A69B4ED686963EE4BDF3DCC4DEAF399D/0?term=2
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
[10:59:32] ERROR java.lang.IllegalStateException: 文件下载失败: https://c2cpicdw.qpic.cn/offpic_new/0/0-0-C19CF40223B46DE0DFAD7ABF9E1A10A4/0?term=2
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

**Comment by fuqiuluo** [comment]
图片地址错误 (不可访问)
导致无法正常上传图片
合成合并转发消息需要上传图片成功

**Comment by ycly901** [comment]
> 图片地址错误 (不可访问) 导致无法正常上传图片 合成合并转发消息需要上传图片成功
大佬，稍微补充一下版本信息，
使用该版本[Shamrock-v1.0.9.r402.661680e-all]，也就是稍微考前一点的版本，合并消息的图片是正常发出的(https://github.com/whitechi73/OpenShamrock/actions/runs/8111360349/artifacts/1289262843)

使用该版本[Shamrock-v1.0.9.r404.d92d1da-all]及之后的，均出现了消息类型不支持查看问题(https://github.com/whitechi73/OpenShamrock/actions/runs/8131794180/artifacts/1293018154)
使用的QQ版本均为9.0.8，是否是Shamrock-v1.0.9.r402.661680e-all该版本后对合并消息进行了改动？

**Comment by ycly901** [comment]
测试发现触发该场景为私聊（三叶草已配置上传资源群聊），群聊的合并消息图片能正常发出，目前发现是私聊才出现该问题

**Comment by chz091** [comment]
> 测试发现触发该场景为私聊（三叶草已配置上传资源群聊），群聊的合并消息图片能正常发出，目前发现是私聊才出现该问题
并且通过私聊发送的合并消息，上传图片还是发送给自己，然后进行转发，并不是发送到配置的上传资源群进行转发
