### ISSUE TITLE
bug: at 消息发送失败 code 35000

### ISSUE THREAD

**Issue by MirrorCY** [whitechi73/OpenShamrock#304]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

在群聊发送 at 消息失败，连接方式为主动 ws
![image](https://github.com/whitechi73/OpenShamrock/assets/37006258/f5305805-17bd-4ba2-ae8f-278db3c9d5f4)

Koishi 日志
```
2024-03-19 02:01:09 [W] session Error: Error with request send_group_msg, args: {"group_id":531961859,"message":[{"type":"at","data":{"qq":"1358688418"}}]}, retcode: 35000
                            at Internal._get (/root/work/koishi-app/node_modules/koishi-plugin-adapter-onebot/lib/types.js:44:15)
                            at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
                            at async Internal.<computed> [as sendGroupMsg] (/root/work/koishi-app/node_modules/koishi-plugin-adapter-onebot/lib/types.js:84:26)
                            at async OneBotMessageEncoder.flush (/root/work/koishi-app/node_modules/koishi-plugin-adapter-onebot/lib/bot/message.js:95:24)
                            at OneBotMessageEncoder.send (/root/work/koishi-app/node_modules/@satorijs/core/src/message.ts:54:5)
                            at OneBotBot.sendMessage (/root/work/koishi-app/node_modules/@satorijs/core/src/bot.ts:169:22)
                            at async Proxy.<anonymous> (/root/work/koishi-app/node_modules/@h4m5ter/koishi-plugin-autowithdraw/lib/index.js:53:25)
                            at <anonymous> (/root/work/koishi-app/node_modules/@koishijs/core/src/session.ts:401:7)
                            at Proxy.withScope (/root/work/koishi-app/node_modules/@koishijs/core/src/session.ts:293:22)
                            at next (/root/work/koishi-app/node_modules/@koishijs/core/src/middleware.ts:259:16)
```

OpenShamrock 日志
```
[02:00:55] INFO 日志框架处于未激活状态，请检查。
[02:00:56] INFO 日志框架激活成功，开放操作许可。
[02:01:09] INFO 群消息(group = 测试群(531961859), uin = 1358688418, id = 1084753391, seq = 3796, msg = echo -E <at id="1358688418">)
[02:01:09] INFO 群消息(group = 测试群(531961859), uin = 2772315229, id = 322410315, seq = 3797, msg = [CQ:at,qq=1358688418])
[02:01:09] ERROR java.lang.NoSuchMethodError: No interface method getTroopMember(Ljava/lang/String;Ljava/lang/String;)Lcom/tencent/mobileqq/data/troop/TroopMemberInfo; in class Lcom/tencent/mobileqq/troop/api/ITroopMemberInfoService; or its super classes (declaration of 'com.tencent.mobileqq.troop.api.ITroopMemberInfoService' appears in base.apk!classes4.dex)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(LimitedDispatcher.kt:115)
	at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:103)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### 复现 Bug

- 创建全新 Koishi 环境
- 安装 onebot 适配器和 echo 插件
- 尝试在群聊使用 echo 插件发送一个 at

## 系统信息

- Shamrock 版本: Shamrock-v1.0.9.r427.7782feb-all
- Android 版本: 13
- LSPosed 框架版本: 1.9.2(7024) - Zygisk
- 设备的制造商和型号: Mi 10 Ultra
- 设备的 CPU 架构: arm64

**Comment by Simplxss** [comment]
QQ版本？

**Comment by MirrorCY** [comment]
v9.0.25.15655
