### ISSUE TITLE
bug: QQ9.0.71异常退出

### ISSUE THREAD

**Issue by lindongbin** [whitechi73/OpenShamrock#338]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/OpenShamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

QQ异常退出

### 复现 Bug

QQ前台挂着就自动退出了
日志里最后一条信息是
WARN OnMessage: com.tencent.mobileqq.pb.InvalidProtocolBufferMicroException: Protocol message tag had invalid wire type.
	at com.tencent.mobileqq.pb.CodedInputStreamMicro.skipField(Unknown Source:25)
	at com.tencent.mobileqq.pb.MessageMicro.parseUnknownField(Unknown Source:0)
	at com.tencent.mobileqq.pb.MessageMicro.mergeFrom(Unknown Source:21)
	at com.tencent.mobileqq.pb.MessageMicro.mergeFrom(Unknown Source:4)
	at com.tencent.mobileqq.pb.MessageMicro.mergeFrom(Unknown Source:2)
	at qq.service.bdh.RichProtoSvc.getGroupFileDownUrl(RichProtoSvc.kt:86)
	at qq.service.bdh.RichProtoSvc$getGroupFileDownUrl$1.invokeSuspend(Unknown Source:18)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.internal.ScopeCoroutine.afterResume(Scopes.kt:28)
	at kotlinx.coroutines.AbstractCoroutine.resumeWith(AbstractCoroutine.kt:99)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:46)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:585)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:802)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:706)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:693)

## 系统信息

- Shamrock 版本: v1.1.0.r1.4adbc12
- Android 版本: 12
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号: mumu模拟器
- 设备的 CPU 架构: x86/64

**Comment by lindongbin** [comment]
![Screenshot_20240712-121747](https://github.com/user-attachments/assets/65d6abcc-5abc-4098-84cc-d5edfb72aad3)
退出的那个时间点是群里有人传了个群文件

**Comment by fuqiuluo** [comment]
提交了，看看能不能用
