### ISSUE TITLE
bug: 正向ws连接时有概率缺失lifecycle信息

### ISSUE THREAD

**Issue by Miuzarte** [whitechi73/OpenShamrock#67]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

正向ws连接到shamrock时有概率收不到lifecycle
因为还没支持/get_login_info，所以暂时通过lifecycle获取自身QQ，然后刚刚突然发现没获取到
重连几下又连着复现了两次
概率不高，现在又复现不了了
shamrock和bot在局域网内的两台不同设备上
我有两个bot连接在同一个shamrock端口上，但是我没法得知另一个bot接收到了什么数据
顺便催一下/get_login_info（（

### 复现 Bug

正向websocket，多次断开重连shamrock

## 系统信息

- Shamrock 版本: [Shamrock-v1.0.5-dev.ca71eca-arm64](https://github.com/whitechi73/OpenShamrock/suites/18318051449/artifacts/1059764525) //不是最新，看了眼没有跟lifecycle有关的commit
- Android 版本: Android 14
- 设备的制造商和型号: Xiaomi Redmi K20 Pro
- 设备的 CPU 架构: Arm64

**Comment by ikechan8370** [comment]
get_login_info不可以吗？

**Comment by whitechi73** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/98259561/62971c00-84b4-46b8-b585-bcffa168654e)

**Comment by Miuzarte** [comment]
> ![image](https://user-images.githubusercontent.com/98259561/284456819-62971c00-84b4-46b8-b585-bcffa168654e.png)

```json
 {"action":"get_login_info","echo":"get_login_info_1700539420675322500"}
```
```log
[12:02:38] WARN java.lang.IllegalStateException: Tag 2 not found
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```
