### ISSUE TITLE
bug: get_login_info未按预期工作

### ISSUE THREAD

**Issue by Miuzarte** [whitechi73/OpenShamrock#68]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

调用get_login_info时无任何响应，日志报warning
POST: 
```json
{"action":"get_login_info","echo":"get_login_info_1700539420675322500"}
```
RECV: 无
```log
[12:02:38] WARN java.lang.IllegalStateException: Tag 2 not found
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

### 复现 Bug

ws正向连接调用get_login_info

## 系统信息

- Shamrock 版本: [Shamrock-v1.0.5-dev.2c49b10](https://github.com/whitechi73/OpenShamrock/actions/runs/6939047600)
- Android 版本: Android 14
- 设备的制造商和型号: Xiaomi Redmi K20 Pro
- 设备的 CPU 架构: Arm64

**Comment by Miuzarte** [comment]
> 即使没有`params`，也要post参数里面有`params`字段。

了解了，从gocq直接转过来发现用不了就直接以为没实现了（
