### ISSUE TITLE
bug: X86发送语音报错

### ISSUE THREAD

**Issue by moesnow** [whitechi73/OpenShamrock#84]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

X86发送语音报错，无论群聊还是私聊，AudioLibrary的架构没有弄错

```
[01:29:05] INFO LoadExternalLibrary(name = ffmpegkit_abidetect)
[01:29:05] INFO LoadExternalLibrary(name = avutil)
[01:29:05] INFO LoadExternalLibrary(name = swscale)
[01:29:05] INFO LoadExternalLibrary(name = swresample)
[01:29:05] INFO LoadExternalLibrary(name = avcodec)
[01:29:05] INFO LoadExternalLibrary(name = avformat)
[01:29:05] INFO LoadExternalLibrary(name = avfilter)
[01:29:05] INFO LoadExternalLibrary(name = avdevice)
[01:29:05] INFO LoadExternalLibrary(name = ffmpegkit)
[01:29:05] INFO LoadExternalLibrary(name = ffmpegkit_abidetect)
[01:29:05] ERROR java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.arthenica.ffmpegkit.AbiDetect.getNativeAbi() (tried Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi and Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi__)
	at com.arthenica.ffmpegkit.AbiDetect.getNativeAbi(Native Method)
	at com.arthenica.ffmpegkit.NativeLoader.loadNativeAbi(NativeLoader.java:65)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKit(NativeLoader.java:173)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.<clinit>(FFmpegKitConfig.java:145)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.parseArguments(FFmpegKitConfig.java:1318)
	at com.arthenica.ffmpegkit.FFmpegKit.execute(FFmpegKit.java:167)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

[01:29:05] ERROR java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.arthenica.ffmpegkit.AbiDetect.getNativeAbi() (tried Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi and Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi__)
	at com.arthenica.ffmpegkit.AbiDetect.getNativeAbi(Native Method)
	at com.arthenica.ffmpegkit.NativeLoader.loadNativeAbi(NativeLoader.java:65)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKit(NativeLoader.java:173)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.<clinit>(FFmpegKitConfig.java:145)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.parseArguments(FFmpegKitConfig.java:1318)
	at com.arthenica.ffmpegkit.FFmpegKit.execute(FFmpegKit.java:167)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

```
[01:34:41] ERROR java.lang.NoClassDefFoundError: com.arthenica.ffmpegkit.FFmpegKitConfig
	at com.arthenica.ffmpegkit.FFmpegKitConfig.parseArguments(FFmpegKitConfig.java:1318)
	at com.arthenica.ffmpegkit.FFmpegKit.execute(FFmpegKit.java:167)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.arthenica.ffmpegkit.AbiDetect.getNativeAbi() (tried Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi and Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi__)
	at com.arthenica.ffmpegkit.AbiDetect.getNativeAbi(Native Method)
	at com.arthenica.ffmpegkit.NativeLoader.loadNativeAbi(NativeLoader.java:65)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKit(NativeLoader.java:173)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.<clinit>(FFmpegKitConfig.java:145)
	... 8 more

[01:34:41] ERROR java.lang.NoClassDefFoundError: com.arthenica.ffmpegkit.FFmpegKitConfig
	at com.arthenica.ffmpegkit.FFmpegKitConfig.parseArguments(FFmpegKitConfig.java:1318)
	at com.arthenica.ffmpegkit.FFmpegKit.execute(FFmpegKit.java:167)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
Caused by: java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.arthenica.ffmpegkit.AbiDetect.getNativeAbi() (tried Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi and Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi__)
	at com.arthenica.ffmpegkit.AbiDetect.getNativeAbi(Native Method)
	at com.arthenica.ffmpegkit.NativeLoader.loadNativeAbi(NativeLoader.java:65)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKit(NativeLoader.java:173)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.<clinit>(FFmpegKitConfig.java:145)
	... 8 more
```

### 复现 Bug

安装 AudioLibrary-x64 后，发送语音文件，肯定没弄错架构

```shell
~/.../Shamrock/lib $ md5sum libffmpegkit.so 
c0dec9eef43e1b61339ebb8bef3a79e5  libffmpegkit.so
```

## 系统信息

- Shamrock 版本: Shamrock-v1.0.6-dev.679b761-x86_64.apk
- Android 版本: 9 (API 28)
- 设备的制造商和型号:  PVE 安装 BlissOS-v11
- 设备的 CPU 架构: X86_64

**Comment by whitechi73** [comment]
两个架构都试试看？

**Comment by moesnow** [comment]
尝试了`AudioLibrary-arm64.zip` 和 `AudioLibrary-x64.zip` 都报错😭

```java
[22:49:55] INFO LoadExternalLibrary(name = ffmpegkit_abidetect)
[22:49:55] INFO LoadExternalLibrary(name = avutil)
[22:49:55] INFO LoadExternalLibrary(name = swscale)
[22:49:55] INFO LoadExternalLibrary(name = swresample)
[22:49:55] INFO LoadExternalLibrary(name = avcodec)
[22:49:55] INFO LoadExternalLibrary(name = avformat)
[22:49:55] INFO LoadExternalLibrary(name = avfilter)
[22:49:55] INFO LoadExternalLibrary(name = avdevice)
[22:49:55] INFO LoadExternalLibrary(name = ffmpegkit)
[22:49:55] INFO LoadExternalLibrary(name = ffmpegkit_abidetect)
[22:49:55] ERROR java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.arthenica.ffmpegkit.AbiDetect.getNativeAbi() (tried Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi and Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi__)
	at com.arthenica.ffmpegkit.AbiDetect.getNativeAbi(Native Method)
	at com.arthenica.ffmpegkit.NativeLoader.loadNativeAbi(NativeLoader.java:65)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKit(NativeLoader.java:173)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.<clinit>(FFmpegKitConfig.java:145)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.parseArguments(FFmpegKitConfig.java:1318)
	at com.arthenica.ffmpegkit.FFmpegKit.execute(FFmpegKit.java:167)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

[22:49:55] ERROR java.lang.UnsatisfiedLinkError: No implementation found for java.lang.String com.arthenica.ffmpegkit.AbiDetect.getNativeAbi() (tried Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi and Java_com_arthenica_ffmpegkit_AbiDetect_getNativeAbi__)
	at com.arthenica.ffmpegkit.AbiDetect.getNativeAbi(Native Method)
	at com.arthenica.ffmpegkit.NativeLoader.loadNativeAbi(NativeLoader.java:65)
	at com.arthenica.ffmpegkit.NativeLoader.loadFFmpegKit(NativeLoader.java:173)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.<clinit>(FFmpegKitConfig.java:145)
	at com.arthenica.ffmpegkit.FFmpegKitConfig.parseArguments(FFmpegKitConfig.java:1318)
	at com.arthenica.ffmpegkit.FFmpegKit.execute(FFmpegKit.java:167)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)
```

**Comment by bowen99** [comment]
![image](https://github.com/whitechi73/OpenShamrock/assets/50953435/1f4270ef-9b40-45e4-bcbd-d581514e7502)
发送语音提示这个

**Comment by okatu-loli** [comment]
遇到同样的问题，查了下似乎是因为缺依赖？
https://github.com/arthenica/ffmpeg-kit/wiki/Smart-Exception-Dependency

**Comment by okatu-loli** [comment]
看到了这个issue，解决了
https://github.com/whitechi73/OpenShamrock/issues/11
