### ISSUE TITLE
bug: 撤回消息上报的消息ID不匹配（无法稳定复现）

### ISSUE THREAD

**Issue by Miuzarte** [whitechi73/OpenShamrock#86]
警告: 在进一步操作之前，请检查下列选项。如果您忽视此模板或者没有提供关键信息，您的 Issue 将直接被关闭
- 确保您使用的是 [最新开发版本](https://github.com/whitechi73/Shamrock/actions/workflows/build-apk.yml) 的 Shamrock.
- 确保您的问题尚未在 Issues 列表中提出.
- 确保您的问题不是由于您的代码错误导致的.

### 描述 Bug

撤回消息上报的消息ID不匹配

~~每次出现这种情况我bot在对撤回的消息排序时就出现空指针，但暂时还没看懂之前我是怎么写的~~

后面复现了再补充吧，~~打游戏去了~~

msgRecv
```json
{
    "time": 1700889372,
    "self_id": self_id,
    "post_type": "message",
    "message_type": "group",
    "sub_type": "normal",
    "message_id": 2002082745,
    "group_id": group_id,
    "peer_id": self_id,
    "user_id": user_id,
    "message": [
        {
            "data": {
                "file": "2dd2413ce83bb05fce1a33ef19c715a9",
                "url": "http://gchat.qpic.cn/gchatpic_new/0/0-0-2DD2413CE83BB05FCE1A33EF19C715A9/0?term=2"
            },
            "type": "image"
        }
    ],
    "raw_message": "[CQ:image,file=2dd2413ce83bb05fce1a33ef19c715a9,url=http://gchat.qpic.cn/gchatpic_new/0/0-0-2DD2413CE83BB05FCE1A33EF19C715A9/0?term=2]",
    "font": 0,
    "sender": {
        "user_id": user_id,
        "nickname": "謬紗特 ",
        "card": "",
        "role": "owner",
        "title": "",
        "level": ""
    }
}
```

msgRecall
```json
{
    "time": 1700889373,
    "self_id": self_id,
    "post_type": "notice",
    "notice_type": "group_recall",
    "group_id": group_id,
    "operator_id": user_id,
    "user_id": user_id,
    "message_id": 987454862
}
```

此时的shamrock日志
```
[13:16:12] INFO 群消息(group = pan.tencent.com<$ÿĀ><$ǿĀ(group_id), uin = user_id, id = 2002082745|12653, msg = [CQ:image,file=2dd2413ce83bb05fce1a33ef19c715a9,url=http://gchat.qpic.cn/gchatpic_new/0/0-0-2DD2413CE83BB05FCE1A33EF19C715A9/0?term=2])
[13:16:13] WARN 不支持的灰条类型(JSON): 17
[13:16:13] INFO 群消息撤回(612645549): user_id -> user_id, seq = 12653, hash = 987454862, tip = 
[13:16:13] WARN java.lang.ClassCastException: moe.fuqiuluo.proto.ProtoByteString cannot be cast to moe.fuqiuluo.proto.ProtoNumber
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

[13:16:13] WARN 不支持的灰条类型(JSON): 17

```

然后我的机器人在缓存中找不到`987454862`这条被撤回的消息
根据日志这个数字是hash字段里出来的
尝试调用`/get_msg`，响应为空，且字段也很奇怪

POST
```json
{"action":"get_msg","echo":"get_msg_1700889372550352400","params":{"message_id":987454862}}
```

RECV
```json
{
    "status": "ok",
    "retcode": 0,
    "data": {
        "time": 1700889373,
        "message_type": "group",
        "message_id": 987454862,
        "real_id": 12653,
        "sender": {
            "user_id": 0,
            "nickname": "pan.tencent.com<$ÿĀ\u0011\u0010><$ǿĀD\u000e>",
            "sex": "unknown",
            "age": 0,
            "uid": ""
        },
        "message": [],
        "group_id": group_id,
        "peer_id": group_id //与group_id相同
    },
    "echo": "get_msg_1700889372550352400"
}
```

### 复现 Bug

发送群消息并撤回

## 系统信息

- Shamrock 版本: [Shamrock-v1.0.6-dev.5062ff7](https://github.com/whitechi73/OpenShamrock/actions/runs/6986860270)
- Android 版本: 14
- 设备的制造商和型号: Redmi K20 Pro
- 设备的 CPU 架构: Arm64

**Comment by Simplxss** [comment]
这堆栈信息压根看不出来哪里报错了...
看起来像是pb模块的问题?
不知道能不能调出详细的堆栈信息, 好定位下问题在哪.

**Comment by whitechi73** [comment]
```log
[13:16:13] WARN java.lang.ClassCastException: moe.fuqiuluo.proto.ProtoByteString cannot be cast to moe.fuqiuluo.proto.ProtoNumber
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)\
```
这条日志是 @ikechan8370 的
```kotlin
onGroupRecall(msgTime, pb)
// invite
onGroupMemIncreased(msgTime, pb)
```
触发的，莫名其妙的。

**Comment by ikechan8370** [comment]
我也看到了

**Comment by ikechan8370** [comment]
> ```
> [13:16:13] WARN java.lang.ClassCastException: moe.fuqiuluo.proto.ProtoByteString cannot be cast to moe.fuqiuluo.proto.ProtoNumber
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
> 	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)\
> ```
> 
> 这条日志是 @ikechan8370 的
> 
> ```kotlin
> onGroupRecall(msgTime, pb)
> // invite
> onGroupMemIncreased(msgTime, pb)
> ```
> 
> 触发的，莫名其妙的。

这个锈掉了。 另外查不到消息是因为撤回的消息机器人本来就查不到了吧？

**Comment by Simplxss** [comment]
如果无法复现就暂时close了 以后遇到再说
