### ISSUE TITLE
Help: websocket接收群友临时消息报错，而且wss没有收到任何信息

### ISSUE THREAD

**Issue by sanlic** [whitechi73/OpenShamrock#95]
websocket接收群友临时消息报错，而且wss没有收到任何信息

报错如下：
WARN java.lang.IllegalStateException: 不支持的消息来源类型 | generateMsgIdHash: 103
	at moe.fuqiuluo.shamrock.helper.MessageHelper.generateMsgIdHash(MessageHelper.kt:110)
	at moe.fuqiuluo.shamrock.remote.service.listener.AioListener.handleMsg(AioListener.kt:32)
	at moe.fuqiuluo.shamrock.remote.service.listener.AioListener.access$handleMsg(AioListener.kt:19)
	at moe.fuqiuluo.shamrock.remote.service.listener.AioListener$onRecvMsg$1.invokeSuspend(AioListener.kt:25)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:108)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:793)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:697)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:684)

- Shamrock 版本: 1.0.5 dev4713310
- Android 版本: 9
- LSPosed 框架版本: 1.9.2
- 设备的制造商和型号:  xiaomi mi6
- 设备的 CPU 架构:  arm64

**Comment by Simplxss** [comment]
**不支持**

**Comment by whitechi73** [comment]
103是来自订阅号的消息。

**Comment by whitechi73** [comment]
群临时消息需要打开开关`"allow-temp-session"`

**Comment by sanlic** [comment]
> 群临时消息需要打开开关`"allow-temp-session"`

已在配置文件里设为true，还是会报错

**Comment by sanlic** [comment]
> 103是来自订阅号的消息。

现在是100报错

**Comment by sanlic** [comment]
最新的开发版可以收到，感谢
